DROP TABLE IF EXISTS `accessibilites`;
CREATE TABLE `accessibilites` (
  `code` char(2) NOT NULL,
  `description` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `aeroport`;
CREATE TABLE `aeroport` (
  `id_aeroport` int(10) NOT NULL AUTO_INCREMENT,
  `code_aeroport` char(3) COLLATE latin1_general_ci NOT NULL,
  `aeroport` varchar(50) CHARACTER SET utf8mb3 NOT NULL,
  `id_lieu` int(10) NOT NULL,
  `pays` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `ville` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `taxe` decimal(3,0) NOT NULL DEFAULT 0,
  `taxe_enfant` decimal(3,0) NOT NULL DEFAULT 0,
  `taxe_bebe` decimal(3,0) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_aeroport`),
  UNIQUE KEY `code_aeroport_unique` (`code_aeroport`)
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `company`;
CREATE TABLE `company` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `company` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `commentaire` text COLLATE latin1_general_ci DEFAULT NULL,
  `photo` text COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `assurance`;
CREATE TABLE `assurance` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titre_assurance` varchar(50) NOT NULL,
  `prix_assurance` decimal(10,2) unsigned NOT NULL DEFAULT 0.00,
  `prestation_assurance` text NOT NULL,
  `couverture` enum('par famille','par personne') NOT NULL,
  `duree` enum('annuelle','voyage') NOT NULL,
  `pourcentage` varchar(20) DEFAULT '0',
  `prix_minimum` decimal(5,2) unsigned DEFAULT NULL,
  `frais_annulation` text NOT NULL,
  `assistance` text NOT NULL,
  `fraisderecherche` text NOT NULL,
  `volretarde` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `chambre`;
CREATE TABLE `chambre` (
  `id_chambre` int(10) NOT NULL AUTO_INCREMENT,
  `nom_chambre` varchar(100) COLLATE latin1_general_ci DEFAULT NULL,
  `id_hotel` int(10) NOT NULL DEFAULT 0,
  `surclassement` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `debut_validite` date NOT NULL DEFAULT '0000-00-00',
  `fin_validite` date NOT NULL DEFAULT '0000-00-00',
  `taux_change` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `taux_commission` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `simple_nb_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `simple_adulte_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `simple_enfant_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `simple_bebe_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_1_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_1_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_1_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `de_1_enfant` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `a_1_enfant` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `enfant_1_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_1_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_1_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `de_2_enfant` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `a_2_enfant` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `enfant_2_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_2_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_2_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `de_3_enfant` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `a_3_enfant` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `enfant_3_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_3_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_3_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `bebe_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `bebe_1_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `bebe_1_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `bebe_1_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_nb_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_1_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_1_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_1_total` decimal(10,2) unsigned NOT NULL DEFAULT 0.00,
  `double_adulte_2_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_2_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_2_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_de_1_enfant` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_a_1_enfant` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_1_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_1_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_1_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_de_2_enfant` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_a_2_enfant` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_2_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_2_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_2_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_de_3_enfant` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_a_3_enfant` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_3_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_3_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_3_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_1_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_1_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_1_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_nb_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_1_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_1_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_1_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_2_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_2_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_2_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_nb_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_max` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_1_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_1_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_1_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_2_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_2_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_2_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_3_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_3_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_3_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_4_net` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_4_brut` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_4_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `club` varchar(250) COLLATE latin1_general_ci DEFAULT NULL,
  `remise` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `unite` enum('pourcentage','chf') COLLATE latin1_general_ci DEFAULT NULL,
  `debut_remise` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `fin_remise` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `debut_remise_voyage` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `fin_remise_voyage` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `status_remise` int(1) DEFAULT NULL,
  `code_promo` varchar(40) COLLATE latin1_general_ci DEFAULT NULL,
  `remise2` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `unite2` enum('pourcentage','chf') COLLATE latin1_general_ci DEFAULT NULL,
  `debut_remise2` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `fin_remise2` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `debut_remise2_voyage` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `fin_remise2_voyage` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `code_promo2` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `photo_chambre` varchar(250) COLLATE latin1_general_ci DEFAULT NULL,
  `tripple_enfant_max` int(2) NOT NULL DEFAULT 0,
  `tripple_adulte_3_net_enfant` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_brut_enfant` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_total_enfant` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `a` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `b` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `monnaie` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `villa_nb_max` int(2) NOT NULL DEFAULT 0,
  `villa_adulte_max` int(2) NOT NULL DEFAULT 0,
  `villa_adulte_1_net` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `villa_adulte_1_brut` varchar(10) COLLATE latin1_general_ci DEFAULT NULL,
  `villa_adulte_1_total` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `disabled` date DEFAULT NULL,
  `quatre_adulte_4_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_4_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_3_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_3_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_2_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_2_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_1_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_1_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_2_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_2_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_1_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_1_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_1_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_1_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_enfant_3_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_3_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_2_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_2_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_1_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_1_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_2_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_2_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_1_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_1_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `bebe_1_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `bebe_1_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_3_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_3_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_2_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_2_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_1_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_1_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_1_total_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_1_net_chf` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_4_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_4_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_3_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_3_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_2_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_2_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_1_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `quatre_adulte_1_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_3_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_2_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_2_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_1_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tripple_adulte_1_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_1_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_bebe_1_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_enfant_3_net_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_3_total_pourcentage` varchar(9) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_2_total_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_2_net_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_1_total_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_enfant_1_net_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_2_total_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_2_net_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_1_total_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `double_adulte_1_net_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `bebe_1_total_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `bebe_1_net_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_3_total_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_3_net_pourcentage` varchar(11) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_2_total_pourcentage` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_2_net_pourcentage` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_1_total_pourcentage` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `enfant_1_net_pourcentage` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_1_total_pourcentage` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `adulte_1_net_pourcentage` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `_villa` tinyint(3) unsigned GENERATED ALWAYS AS (`villa_nb_max` > 0) VIRTUAL,
  `_nb_min` tinyint(3) unsigned GENERATED ALWAYS AS (ifnull(nullif(least(ifnull(nullif((`simple_nb_max` > 0) * `simple_adulte_max`,0) + 0,99),ifnull(nullif((`double_nb_max` > 0) * `double_adulte_max`,0) + 0,99),ifnull(nullif((`tripple_nb_max` > 0) * `tripple_adulte_max`,0) + 0,99),ifnull(nullif((`quatre_nb_max` > 0) * `quatre_adulte_max`,0) + 0,99)),99),1)) VIRTUAL,
  `_nb_max` tinyint(3) unsigned GENERATED ALWAYS AS (greatest(`simple_nb_max`,`double_nb_max`,`tripple_nb_max`,`quatre_nb_max`,`villa_nb_max`) + 0) VIRTUAL,
  `_nb_max_adulte` tinyint(3) unsigned GENERATED ALWAYS AS (greatest((`simple_nb_max` > 0) * `simple_adulte_max`,(`double_nb_max` > 0) * `double_adulte_max`,(`tripple_nb_max` > 0) * `tripple_adulte_max`,(`quatre_nb_max` > 0) * `quatre_adulte_max`,`villa_nb_max`)) VIRTUAL,
  `_nb_max_enfant` tinyint(3) unsigned GENERATED ALWAYS AS (greatest(`simple_enfant_max`,`double_enfant_max`,`tripple_enfant_max`,`villa_nb_max` - 1)) VIRTUAL,
  `_nb_max_bebe` tinyint(3) unsigned GENERATED ALWAYS AS (greatest(`simple_bebe_max`,`double_bebe_max`)) VIRTUAL,
  `_age_max_bebe` tinyint(3) unsigned GENERATED ALWAYS AS (greatest(0,(`simple_bebe_max` > 0 and `bebe_1` > '') * `bebe_1`,(`double_bebe_max` > 0 and `double_bebe_1` > '') * `double_bebe_1`,(`_nb_max_bebe` <> 0 and `_nb_max_enfant` <> 0) * cast(`de_1_enfant` as signed) - 1,(`_nb_max_bebe` <> 0 and `_nb_max_enfant` <> 0) * cast(`double_de_1_enfant` as signed) - 1)) VIRTUAL,
  `_age_max_petit_enfant` tinyint(3) unsigned GENERATED ALWAYS AS (coalesce(if(`simple_enfant_max` = 0,NULL,`a_1_enfant`),if(`double_enfant_max` = 0,NULL,`double_a_1_enfant`))) VIRTUAL,
  `_age_max_enfant` tinyint(3) unsigned GENERATED ALWAYS AS (nullif((`_nb_max_enfant` > 0) * greatest(`a_1_enfant`,`a_2_enfant`,`double_a_1_enfant`,`double_a_2_enfant`),0)) VIRTUAL,
  `_enfant_2_net` decimal(5,1) unsigned GENERATED ALWAYS AS (greatest(`enfant_1_net` + 0,`enfant_2_net` + 0,`enfant_3_net` + 0,`double_enfant_1_net` + 0,`double_enfant_2_net` + 0,`double_enfant_3_net` + 0)) VIRTUAL COMMENT 'appliqué au 1er enfant si age <= age_max_petit_enfant',
  `_enfant_1_net` decimal(5,1) unsigned GENERATED ALWAYS AS (if(`_age_max_petit_enfant` > 0,greatest(`enfant_1_net`,`double_enfant_1_net`),NULL)) VIRTUAL COMMENT 'appliqué au 2èm enfant, et au 1er enfant si son age > age_max_petit_enfant',
  `_adulte_1_net_a` decimal(6,2) GENERATED ALWAYS AS (`a`) VIRTUAL,
  `_adulte_1_net_b` decimal(6,2) GENERATED ALWAYS AS (`b`) VIRTUAL,
  `_adulte_1_net` decimal(6,2) GENERATED ALWAYS AS (if(`_villa`,`villa_adulte_1_net`,if(`_nb_min` = 1,ceiling(`a` + `b`),NULL))) VIRTUAL COMMENT 'appliqué s''il n''y a qu''un adulte.',
  `_adulte_2_net` decimal(6,2) GENERATED ALWAYS AS (if(`_nb_max_adulte` < 2,NULL,`double_adulte_2_net`)) VIRTUAL COMMENT 'appliqué aux 1er et 2èm adultes si nb_adultes > 1',
  `_adulte_3_net` decimal(6,2) GENERATED ALWAYS AS (if(`_nb_max_adulte` < 3,NULL,nullif(greatest(`tripple_adulte_3_net`,`quatre_adulte_3_net`),`_adulte_1_net`))) VIRTUAL,
  `_adulte_4_net` decimal(6,2) GENERATED ALWAYS AS (if(`_nb_max_adulte` < 4,NULL,nullif(`quatre_adulte_3_net`,`_adulte_3_net`))) VIRTUAL,
  `_bebe_1_net` decimal(6,2) GENERATED ALWAYS AS (if(`_nb_max_bebe`,`bebe_1_net`,NULL)) VIRTUAL,
  PRIMARY KEY (`id_chambre`),
  KEY `chambre_hotel_FK` (`id_hotel`)
) ENGINE=InnoDB AUTO_INCREMENT=10113 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `circuits_new`;
CREATE TABLE `circuits_new` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `titre` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `tour_code` varchar(20) COLLATE latin1_general_ci DEFAULT NULL,
  `id_lieu_dpt` int(10) DEFAULT NULL,
  `id_lieu_arr` int(10) DEFAULT NULL,
  `jours_depart` set('1','2','3','4','5','6','7') COLLATE latin1_general_ci NOT NULL DEFAULT '1,2,3,4,5,6,7',
  `dates_depart` longtext COLLATE latin1_general_ci DEFAULT NULL,
  `nb_nuit` tinyint(3) unsigned NOT NULL DEFAULT 1,
  `type_repas` enum('Selon programme','Sans repas','Petit déjeuner') COLLATE latin1_general_ci NOT NULL DEFAULT 'Selon programme',
  `type_circuit` enum('Privé','Collectif') COLLATE latin1_general_ci NOT NULL,
  `langue` enum('Francophone','Anglophone') COLLATE latin1_general_ci NOT NULL DEFAULT 'Francophone',
  `debut_validite` date NOT NULL,
  `fin_validite` date NOT NULL,
  `photo` varchar(40) COLLATE latin1_general_ci DEFAULT NULL,
  `remise_pct` tinyint(3) unsigned DEFAULT 0,
  `remise_debut` date DEFAULT NULL,
  `remise_fin` date DEFAULT NULL,
  `remise_debut_voyage` date DEFAULT NULL,
  `remise_fin_voyage` date DEFAULT NULL,
  `remise_code_promo` varchar(50) COLLATE latin1_general_ci DEFAULT '',
  `inclus` text COLLATE latin1_general_ci DEFAULT NULL,
  `non_inclus` text COLLATE latin1_general_ci DEFAULT NULL,
  `id_vol` int(15) NOT NULL DEFAULT 0,
  `slug` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `monnaie` char(3) COLLATE latin1_general_ci DEFAULT NULL,
  `taux_change` float NOT NULL DEFAULT 0,
  `taux_commission` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_nb_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_adulte_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_bebe_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_adulte_1_net_a` decimal(8,2) DEFAULT NULL,
  `simple_adulte_1_net_b` decimal(8,2) DEFAULT NULL,
  `simple_adulte_1_brut` decimal(8,2) DEFAULT NULL,
  `simple_adulte_1_total` decimal(8,2) DEFAULT NULL,
  `simple_enfant_1_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_1_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_1_net` decimal(8,2) DEFAULT NULL,
  `simple_enfant_1_brut` decimal(8,2) DEFAULT NULL,
  `simple_enfant_1_total` decimal(8,2) DEFAULT NULL,
  `simple_enfant_2_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_2_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_2_net` decimal(8,2) DEFAULT NULL,
  `simple_enfant_2_brut` decimal(8,2) DEFAULT NULL,
  `simple_enfant_2_total` decimal(8,2) DEFAULT NULL,
  `simple_enfant_3_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_3_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_3_net` decimal(8,2) DEFAULT NULL,
  `simple_enfant_3_brut` decimal(8,2) DEFAULT NULL,
  `simple_enfant_3_total` decimal(8,2) DEFAULT NULL,
  `simple_bebe_1_agemax` tinyint(3) DEFAULT NULL,
  `simple_bebe_1_net` decimal(8,2) DEFAULT NULL,
  `simple_bebe_1_brut` decimal(8,2) DEFAULT NULL,
  `simple_bebe_1_total` decimal(8,2) DEFAULT NULL,
  `double_nb_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_adulte_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_bebe_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_adulte_1_net` decimal(8,2) DEFAULT NULL,
  `double_adulte_1_brut` decimal(8,2) DEFAULT NULL,
  `double_adulte_1_total` decimal(8,2) DEFAULT NULL,
  `double_adulte_2_net` decimal(8,2) DEFAULT NULL,
  `double_adulte_2_brut` decimal(8,2) DEFAULT NULL,
  `double_adulte_2_total` decimal(8,2) DEFAULT NULL,
  `double_enfant_1_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_1_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_1_net` decimal(8,2) DEFAULT NULL,
  `double_enfant_1_brut` decimal(8,2) DEFAULT NULL,
  `double_enfant_1_total` decimal(8,2) DEFAULT NULL,
  `double_enfant_2_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_2_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_2_net` decimal(8,2) DEFAULT NULL,
  `double_enfant_2_brut` decimal(8,2) DEFAULT NULL,
  `double_enfant_2_total` decimal(8,2) DEFAULT NULL,
  `double_enfant_3_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_3_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_3_net` decimal(8,2) DEFAULT NULL,
  `double_enfant_3_brut` decimal(8,2) DEFAULT NULL,
  `double_enfant_3_total` decimal(8,2) DEFAULT NULL,
  `double_bebe_1_agemax` tinyint(1) DEFAULT NULL,
  `double_bebe_1_net` decimal(8,2) DEFAULT NULL,
  `double_bebe_1_brut` decimal(8,2) DEFAULT NULL,
  `double_bebe_1_total` decimal(8,2) DEFAULT NULL,
  `tripple_nb_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `tripple_enfant_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `tripple_adulte_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `tripple_adulte_1_net` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_1_brut` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_1_total` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_2_net` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_2_brut` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_2_total` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_3_net` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_3_brut` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_3_total` decimal(8,2) DEFAULT NULL,
  `quatre_nb_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `quatre_adulte_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `quatre_adulte_1_net` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_1_brut` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_1_total` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_2_net` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_2_brut` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_2_total` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_3_net` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_3_brut` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_3_total` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_4_net` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_4_brut` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_4_total` decimal(8,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=315 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `croisieres_new`;
CREATE TABLE `croisieres_new` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `titre` varchar(50) NOT NULL,
  `tour_code` varchar(20) DEFAULT NULL,
  `id_lieu_dpt` int(10) DEFAULT NULL,
  `id_lieu_arr` int(10) DEFAULT NULL,
  `jours_depart` set('1','2','3','4','5','6','7') NOT NULL DEFAULT '1,2,3,4,5,6,7',
  `dates_depart` text DEFAULT NULL,
  `nb_nuit` tinyint(3) unsigned NOT NULL DEFAULT 1,
  `type_repas` enum('Sans repas','Petit déjeuner','Demi-pension','Pension complète','All Inclusive','Selon programme') NOT NULL DEFAULT 'Selon programme',
  `type_depart` enum('quotidien','programmé') NOT NULL,
  `type_croisiere` enum('maritime','fluviale') NOT NULL,
  `debut_validite` date NOT NULL,
  `fin_validite` date NOT NULL,
  `photo` varchar(40) DEFAULT NULL,
  `remise_pct` tinyint(3) unsigned DEFAULT 0,
  `remise_debut` date DEFAULT NULL,
  `remise_fin` date DEFAULT NULL,
  `remise_debut_voyage` date DEFAULT NULL,
  `remise_fin_voyage` date DEFAULT NULL,
  `remise_code_promo` varchar(50) DEFAULT '',
  `inclus` text DEFAULT NULL,
  `non_inclus` text DEFAULT NULL,
  `id_vol` int(15) NOT NULL DEFAULT 0,
  `monnaie` char(3) DEFAULT NULL,
  `taux_change` float NOT NULL DEFAULT 0,
  `taux_commission` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_nb_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_adulte_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_bebe_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_adulte_1_net_a` decimal(8,2) DEFAULT NULL,
  `simple_adulte_1_net_b` decimal(8,2) DEFAULT NULL,
  `simple_adulte_1_brut` decimal(8,2) DEFAULT NULL,
  `simple_adulte_1_total` decimal(8,2) DEFAULT NULL,
  `simple_enfant_1_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_1_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_1_net` decimal(8,2) DEFAULT NULL,
  `simple_enfant_1_brut` decimal(8,2) DEFAULT NULL,
  `simple_enfant_1_total` decimal(8,2) DEFAULT NULL,
  `simple_enfant_2_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_2_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_2_net` decimal(8,2) DEFAULT NULL,
  `simple_enfant_2_brut` decimal(8,2) DEFAULT NULL,
  `simple_enfant_2_total` decimal(8,2) DEFAULT NULL,
  `simple_enfant_3_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_3_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `simple_enfant_3_net` decimal(8,2) DEFAULT NULL,
  `simple_enfant_3_brut` decimal(8,2) DEFAULT NULL,
  `simple_enfant_3_total` decimal(8,2) DEFAULT NULL,
  `simple_bebe_1_agemax` tinyint(3) DEFAULT NULL,
  `simple_bebe_1_net` decimal(8,2) DEFAULT NULL,
  `simple_bebe_1_brut` decimal(8,2) DEFAULT NULL,
  `simple_bebe_1_total` decimal(8,2) DEFAULT NULL,
  `double_nb_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_adulte_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_bebe_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_adulte_1_net` decimal(8,2) DEFAULT NULL,
  `double_adulte_1_brut` decimal(8,2) DEFAULT NULL,
  `double_adulte_1_total` decimal(8,2) DEFAULT NULL,
  `double_adulte_2_net` decimal(8,2) DEFAULT NULL,
  `double_adulte_2_brut` decimal(8,2) DEFAULT NULL,
  `double_adulte_2_total` decimal(8,2) DEFAULT NULL,
  `double_enfant_1_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_1_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_1_net` decimal(8,2) DEFAULT NULL,
  `double_enfant_1_brut` decimal(8,2) DEFAULT NULL,
  `double_enfant_1_total` decimal(8,2) DEFAULT NULL,
  `double_enfant_2_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_2_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_2_net` decimal(8,2) DEFAULT NULL,
  `double_enfant_2_brut` decimal(8,2) DEFAULT NULL,
  `double_enfant_2_total` decimal(8,2) DEFAULT NULL,
  `double_enfant_3_agemin` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_3_agemax` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `double_enfant_3_net` decimal(8,2) DEFAULT NULL,
  `double_enfant_3_brut` decimal(8,2) DEFAULT NULL,
  `double_enfant_3_total` decimal(8,2) DEFAULT NULL,
  `double_bebe_1_agemax` tinyint(1) DEFAULT NULL,
  `double_bebe_1_net` decimal(8,2) DEFAULT NULL,
  `double_bebe_1_brut` decimal(8,2) DEFAULT NULL,
  `double_bebe_1_total` decimal(8,2) DEFAULT NULL,
  `tripple_nb_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `tripple_enfant_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `tripple_adulte_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `tripple_adulte_1_net` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_1_brut` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_1_total` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_2_net` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_2_brut` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_2_total` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_3_net` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_3_brut` decimal(8,2) DEFAULT NULL,
  `tripple_adulte_3_total` decimal(8,2) DEFAULT NULL,
  `quatre_nb_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `quatre_adulte_max` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `quatre_adulte_1_net` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_1_brut` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_1_total` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_2_net` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_2_brut` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_2_total` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_3_net` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_3_brut` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_3_total` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_4_net` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_4_brut` decimal(8,2) DEFAULT NULL,
  `quatre_adulte_4_total` decimal(8,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `hotels_new`;
CREATE TABLE `hotels_new` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(50) CHARACTER SET utf8mb4 NOT NULL,
  `etoiles` tinyint(3) unsigned NOT NULL,
  `situation` enum('Bord de mer','Montagne','Plage','Ville') COLLATE latin1_general_ci NOT NULL,
  `ville_lieu` varchar(100) COLLATE latin1_general_ci DEFAULT NULL COMMENT 'champ temporaire, à supprimer après correction id_lieu',
  `id_lieu` int(10) unsigned NOT NULL,
  `adresse` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
  `postal_code` varchar(9) COLLATE latin1_general_ci NOT NULL,
  `tel` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `mail` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `photo` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `age_minimum` tinyint(4) NOT NULL,
  `repas` enum('Petit déjeuner','Demi-pension','All Inclusive','Ultra All Inclusive') COLLATE latin1_general_ci NOT NULL DEFAULT 'Petit déjeuner',
  `slug` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `coup_coeur` tinyint(1) NOT NULL,
  `decouvrir` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `hotels_new_id_lieu_IDX` (`id_lieu`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=229 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `prestation_hotel`;
CREATE TABLE `prestation_hotel` (
  `id_prestation_hotel` int(15) NOT NULL AUTO_INCREMENT,
  `id_hotel` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `id_partenaire` varchar(15) COLLATE latin1_general_ci NOT NULL,
  `debut_validite` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `fin_validite` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `taux_change` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `monnaie` char(3) COLLATE latin1_general_ci DEFAULT NULL,
  `taux_commission` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `prix_net_adulte` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `prix_brute_adulte` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `total_adulte` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `prix_net_enfant` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `prix_brute_enfant` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `total_enfant` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `prix_net_bebe` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `prix_brute_bebe` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `total_bebe` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `photo` text COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id_prestation_hotel`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `lieux`;
CREATE TABLE `lieux` (
  `id_lieu` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code_pays` varchar(2) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `pays` varchar(50) NOT NULL,
  `region` varchar(50) DEFAULT NULL,
  `ville` varchar(50) NOT NULL,
  `ville_key` varchar(55) GENERATED ALWAYS AS (concat(convert(`code_pays` using utf8mb3),'-',`ville`)) VIRTUAL COMMENT 'Use this for JOINs by ville',
  `lieu` varchar(150) NOT NULL DEFAULT '',
  `photo_lieu` varchar(250) DEFAULT NULL,
  `region_key` varchar(55) GENERATED ALWAYS AS (crc32(concat(convert(`code_pays` using utf8mb3),'-',`region`))) STORED COMMENT 'Use this for JOINs by region',
  PRIMARY KEY (`id_lieu`),
  KEY `region_key` (`region_key`),
  KEY `code_pays` (`code_pays`,`region`)
) ENGINE=MyISAM AUTO_INCREMENT=1685 DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `taux_monnaie`;
CREATE TABLE `taux_monnaie` (
  `id_taux_monnaie` int(10) NOT NULL AUTO_INCREMENT,
  `nom_monnaie` varchar(30) COLLATE latin1_general_ci NOT NULL,
  `code` char(3) COLLATE latin1_general_ci NOT NULL,
  `taux` float NOT NULL,
  PRIMARY KEY (`id_taux_monnaie`),
  UNIQUE KEY `taux_monnaie_code_unique` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `partenaire`;
CREATE TABLE `partenaire` (
  `id_partenaire` int(15) NOT NULL AUTO_INCREMENT,
  `nom_partenaire` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `id_lieu` int(3) NOT NULL DEFAULT 0,
  `adresse` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `codepostal` varchar(10) COLLATE latin1_general_ci NOT NULL,
  `telephone_hotel` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `adresse_reservation` varchar(50) COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id_partenaire`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `pays`;
CREATE TABLE `pays` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `code` char(2) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `nom_en_gb` varchar(45) NOT NULL,
  `nom_fr_fr` varchar(45) NOT NULL,
  `continent` varchar(50) DEFAULT NULL,
  `ISO-3166-1-num` int(3) DEFAULT NULL,
  `ISO-3166-1-a3` varchar(3) DEFAULT NULL,
  `visa_enfant` tinyint(3) unsigned DEFAULT NULL COMMENT 'Prix CHF du visa obligatoire (frais commande inclus)',
  `visa_adulte` tinyint(3) unsigned DEFAULT NULL COMMENT 'Prix CHF du visa obligatoire (frais commande inclus)',
  `visa_bebe` tinyint(3) unsigned DEFAULT NULL COMMENT 'Prix CHF du visa obligatoire (frais commande inclus)',
  `obligatoire` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `alpha2` (`code`),
  UNIQUE KEY `alpha3` (`ISO-3166-1-a3`),
  UNIQUE KEY `code_unique` (`ISO-3166-1-num`)
) ENGINE=MyISAM AUTO_INCREMENT=243 DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `prestations`;
CREATE TABLE `prestations` (
  `id` int(15) NOT NULL AUTO_INCREMENT,
  `provider_id` int(10) unsigned NOT NULL,
  `provider_type` enum('App\\Models\\Hotel','App\\Models\\Circuit','App\\Models\\Croisiere') COLLATE latin1_general_ci NOT NULL,
  `id_type` int(10) DEFAULT NULL COMMENT 'refers to tbloption',
  `name` varchar(100) CHARACTER SET utf8mb4 DEFAULT NULL,
  `description` mediumtext CHARACTER SET utf8mb4 DEFAULT NULL,
  `obligatoire` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `debut_validite` date NOT NULL,
  `fin_validite` date NOT NULL,
  `code_monnaie` char(3) COLLATE latin1_general_ci NOT NULL,
  `taux_commission` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `adulte_net` decimal(6,2) unsigned DEFAULT NULL,
  `enfant_net` decimal(6,2) unsigned DEFAULT NULL,
  `bebe_net` decimal(6,2) unsigned DEFAULT NULL,
  `photo` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `owner_type_owner_id` (`provider_type`,`provider_id`),
  KEY `id_partenaire` (`id_type`)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `recommandations`;
CREATE TABLE `recommandations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(100) NOT NULL,
  `icone` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `reservations`;
CREATE TABLE `reservations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code_pays` char(2) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL COMMENT 'Destination',
  `date_depart` date NOT NULL,
  `date_retour` date NOT NULL,
  `nb_adulte` tinyint(3) unsigned DEFAULT NULL,
  `ages_enfants` varchar(20) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL COMMENT 'comma-separated ages (int)',
  `nb_bebe` tinyint(3) unsigned DEFAULT NULL,
  `id_prix_vol` int(10) DEFAULT NULL,
  `id_transfert` int(10) DEFAULT NULL,
  `id_chambre` int(10) DEFAULT NULL,
  `nb_chambres` tinyint(3) unsigned NOT NULL DEFAULT 1,
  `nom_chambre` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'info pour référence, ne pas utiliser dans le code',
  `id_hotel` int(10) DEFAULT NULL COMMENT 'info pour référence, ne pas utiliser dans le code',
  `contact_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `remarques` text CHARACTER SET utf8mb4 DEFAULT NULL,
  `pdf_devis_filename` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `client_submitted_at` timestamp NULL DEFAULT NULL,
  `quote_sent_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `id_prix_vol` (`id_prix_vol`),
  KEY `id_transfert` (`id_transfert`),
  KEY `id_chambre` (`id_chambre`),
  CONSTRAINT `reservations_ibfk_1` FOREIGN KEY (`id_prix_vol`) REFERENCES `vol_prix` (`id_prix_vol`),
  CONSTRAINT `reservations_ibfk_2` FOREIGN KEY (`id_transfert`) REFERENCES `transfert_new` (`id`),
  CONSTRAINT `reservations_ibfk_3` FOREIGN KEY (`id_chambre`) REFERENCES `chambre` (`id_chambre`)
) ENGINE=InnoDB AUTO_INCREMENT=107 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `reservation_info`;
CREATE TABLE `reservation_info` (
  `id_reservation_info` int(15) NOT NULL AUTO_INCREMENT,
  `id_reservation_valeur` int(15) NOT NULL DEFAULT 0,
  `titre_participant_1` varchar(50) COLLATE latin1_general_ci DEFAULT '0',
  `nom_participant_1` varchar(50) COLLATE latin1_general_ci DEFAULT '0',
  `prenom_participant_1` varchar(50) COLLATE latin1_general_ci DEFAULT '0',
  `nationalite_participant_1` varchar(50) COLLATE latin1_general_ci DEFAULT '0',
  `assurance_1` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `titre_participant_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nom_participant_2` varchar(50) COLLATE latin1_general_ci DEFAULT '0',
  `prenom_participant_2` varchar(50) COLLATE latin1_general_ci DEFAULT '0',
  `nationalite_participant_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `assurance_2` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `titre_participant_3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nom_participant_3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prenom_participant_3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nationalite_participant_3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `assurance_3` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `titre_participant_4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nom_participant_4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prenom_participant_4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nationalite_participant_4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `assurance_4` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `titre_participant_enfant_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nom_participant_enfant_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prenom_participant_enfant_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `date_naissance_participant_enfant_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nationalite_participant_enfant_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `assurance_enfant_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `titre_participant_enfant_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nom_participant_enfant_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prenom_participant_enfant_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `date_naissance_participant_enfant_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nationalite_participant_enfant_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `assurance_enfant_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `titre_participant_bebe_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nom_participant_bebe_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prenom_participant_bebe_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `date_naissance_participant_bebe_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nationalite_participant_bebe_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `assurance_bebe_1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `titre_participant_bebe_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nom_participant_bebe_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prenom_participant_bebe_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `date_naissance_participant_bebe_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nationalite_participant_bebe_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `assurance_bebe_2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `titre_coordonnee` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `nom` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prenom` varchar(80) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `rue` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `npa` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `lieu` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `pays` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `email` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `reemail` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `tel` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `paiement` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `cgcv` int(10) NOT NULL DEFAULT 0,
  `document` int(10) NOT NULL DEFAULT 0,
  `newsletter` int(10) NOT NULL DEFAULT 0,
  `prix_chambre_a1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_chambre_a2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_chambre_a3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_chambre_a4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_chambre_e1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_chambre_e2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_chambre_b1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_transfert_a1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_transfert_a2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_transfert_a3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_transfert_a4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_transfert_e1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_transfert_e2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_transfert_b1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_visa_a1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_visa_a2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_visa_a3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_visa_a4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_visa_e1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_visa_e2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_visa_b1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_option_a1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_option_a2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_option_a3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_option_a4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_option_e1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_option_e2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_option_b1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_repas_a1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_repas_a2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_repas_a3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_repas_a4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_repas_e1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_repas_e2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_repas_b1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_tour_a1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_tour_a2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_tour_a3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_tour_a4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_tour_e1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_tour_e2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_tour_b1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_total_a1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_total_a2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_total_a3` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_total_a4` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_total_e1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_total_e2` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_total_b1` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `prix_total_total` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `id_prest1` int(50) NOT NULL DEFAULT 0,
  `id_prest2` int(50) NOT NULL DEFAULT 0,
  `id_prest3` int(50) NOT NULL DEFAULT 0,
  `id_prest4` int(50) NOT NULL DEFAULT 0,
  `id_prest5` int(50) NOT NULL DEFAULT 0,
  `id_prix_repas_obligatoire` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `option_autre_transfert` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `option_autre_transfert_enfant` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `option_autre_transfert_bebe` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `id_option_autre_transfert` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `id_option_autre_transfert_enfant` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `id_option_autre_transfert_bebe` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `id_prix_transfert_obligatoire` varchar(50) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `devis` int(11) NOT NULL,
  `date_creation` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `status` int(2) NOT NULL,
  `num_rue` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `titre_ass_1` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `titre_ass_2` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `titre_ass_3` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `titre_ass_4` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `id_assurance_1` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `id_assurance_2` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `id_assurance_3` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `id_assurance_4` varchar(10) COLLATE latin1_general_ci NOT NULL DEFAULT '0',
  `check_assurance_adulte_1` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_assurance_adulte_2` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_assurance_adulte_3` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_assurance_adulte_4` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_repas_adulte_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_repas_enfant_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_repas_bebe_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_prestation_adulte_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_prestation_enfant_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_prestation_bebe_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_excursion_adulte_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_excursion_enfant_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_excursion_bebe_101` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_excursion_adulte_201` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_excursion_enfant_201` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `check_excursion_bebe_201` varchar(5) COLLATE latin1_general_ci NOT NULL DEFAULT '1',
  `remarque` text COLLATE latin1_general_ci DEFAULT NULL,
  `commentaire` text COLLATE latin1_general_ci DEFAULT NULL,
  PRIMARY KEY (`id_reservation_info`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `reservation_prestation`;
CREATE TABLE `reservation_prestation` (
  `reservation_id` int(10) unsigned NOT NULL,
  `prestation_id` int(15) NOT NULL,
  `adulte` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'number of adultes',
  `enfant` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'number of children',
  `bebe` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'number of babies',
  KEY `id_prestation` (`prestation_id`),
  KEY `id_reservation` (`reservation_id`),
  CONSTRAINT `reservation_prestation_ibfk_3` FOREIGN KEY (`prestation_id`) REFERENCES `prestations` (`id`),
  CONSTRAINT `reservation_prestation_ibfk_4` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `reservation_tour`;
CREATE TABLE `reservation_tour` (
  `reservation_id` int(10) unsigned NOT NULL,
  `tour_id` int(15) NOT NULL,
  `adulte` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'number of adultes',
  `enfant` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'number of children',
  `bebe` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'number of babies',
  KEY `tours_id` (`tour_id`),
  KEY `reservation_id` (`reservation_id`),
  CONSTRAINT `reservation_tour_ibfk_2` FOREIGN KEY (`tour_id`) REFERENCES `tours_new` (`id`),
  CONSTRAINT `reservation_tour_ibfk_3` FOREIGN KEY (`reservation_id`) REFERENCES `reservations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `sejours`;
CREATE TABLE `sejours` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `titre` varchar(250) NOT NULL,
  `id_vol` int(10) NOT NULL,
  `id_transfert` int(10) NOT NULL,
  `id_chambre` int(10) NOT NULL,
  `debut_vente` date NOT NULL,
  `fin_vente` date NOT NULL,
  `debut_voyage` date NOT NULL,
  `fin_voyage` date NOT NULL,
  `nb_nuit` tinyint(4) NOT NULL DEFAULT 1,
  `promo` tinyint(1) NOT NULL DEFAULT 0,
  `avant` tinyint(1) NOT NULL DEFAULT 0,
  `coup_coeur` tinyint(1) NOT NULL DEFAULT 0,
  `manuel` tinyint(1) NOT NULL DEFAULT 0,
  `photo` varchar(100) NOT NULL DEFAULT '',
  `inclu` text NOT NULL DEFAULT '',
  `noninclu` text NOT NULL DEFAULT '',
  `simple_adulte_1` decimal(6,0) DEFAULT NULL,
  `double_enfant_1a` decimal(6,0) DEFAULT NULL,
  `double_enfant_1b` decimal(6,0) DEFAULT NULL,
  `simple_enfant_1a` decimal(6,0) DEFAULT NULL,
  `simple_enfant_1b` decimal(6,0) DEFAULT NULL,
  `simple_enfant_2` decimal(6,0) DEFAULT NULL,
  `simple_bebe` decimal(6,0) DEFAULT NULL,
  `double_adulte_1` decimal(6,0) DEFAULT NULL,
  `double_adulte_2` decimal(6,0) DEFAULT NULL,
  `double_enfant_2` decimal(6,0) DEFAULT NULL,
  `double_bebe` decimal(6,0) DEFAULT NULL,
  `triple_adulte_1` decimal(6,0) DEFAULT NULL,
  `triple_adulte_2` decimal(6,0) DEFAULT NULL,
  `triple_adulte_3` decimal(6,0) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=339 DEFAULT CHARSET=utf8mb3;

DROP TABLE IF EXISTS `tours_new`;
CREATE TABLE `tours_new` (
  `id` int(15) NOT NULL AUTO_INCREMENT,
  `nom` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `id_partenaire` int(10) NOT NULL,
  `id_lieu` int(10) NOT NULL,
  `jours_depart` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `langue` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `debut_validite` date NOT NULL,
  `fin_validite` date NOT NULL,
  `monnaie` char(3) COLLATE latin1_general_ci DEFAULT NULL,
  `taux_change` float NOT NULL,
  `taux_commission` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `id_type_tour` int(10) NOT NULL,
  `duree` varchar(25) COLLATE latin1_general_ci NOT NULL,
  `photo` varchar(40) COLLATE latin1_general_ci NOT NULL,
  `prix_net_adulte` decimal(7,2) NOT NULL DEFAULT 0.00,
  `prix_total_adulte` decimal(7,2) NOT NULL DEFAULT 0.00,
  `prix_net_enfant` decimal(7,2) NOT NULL DEFAULT 0.00,
  `prix_total_enfant` decimal(7,2) NOT NULL DEFAULT 0.00,
  `prix_net_bebe` decimal(7,2) NOT NULL DEFAULT 0.00,
  `prix_total_bebe` decimal(7,2) NOT NULL DEFAULT 0.00,
  `detail` varchar(500) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `programme` text COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `inclus` text COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `noninclus` text COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `duree_trajet` varchar(100) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `facilite` enum('Facile','Moyen','Difficile') COLLATE latin1_general_ci NOT NULL DEFAULT 'Facile',
  `accessibiltes` varchar(200) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `recommandations` varchar(100) COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=235 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `type_tour`;
CREATE TABLE `type_tour` (
  `id_type` int(10) NOT NULL AUTO_INCREMENT,
  `nom_type` varchar(50) COLLATE latin1_general_ci NOT NULL,
  `photo` text COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id_type`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `transfert_new`;
CREATE TABLE `transfert_new` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `titre` varchar(150) COLLATE latin1_general_ci NOT NULL,
  `type` enum('car','hydravion','speedboat') COLLATE latin1_general_ci NOT NULL DEFAULT 'car',
  `dpt_code_aeroport` char(3) COLLATE latin1_general_ci NOT NULL COMMENT 'début du tranfert - code de l''aéroport',
  `arv_id_hotel` int(10) NOT NULL COMMENT 'arrivée du tranfert - id de l''hotel',
  `id_partenaire` int(10) DEFAULT NULL,
  `debut_validite` date NOT NULL,
  `fin_validite` date NOT NULL,
  `monnaie` char(3) COLLATE latin1_general_ci NOT NULL,
  `taux_change` float unsigned NOT NULL,
  `taux_commission` smallint(5) unsigned DEFAULT NULL,
  `photo` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `service` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `adulte_comm` smallint(5) unsigned DEFAULT NULL,
  `enfant_comm` smallint(5) unsigned DEFAULT NULL,
  `bebe_comm` smallint(5) unsigned DEFAULT NULL,
  `frais_priseencharge` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `adulte_a_net_1` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_a_brut_1` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_r_net_1` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_r_brut_1` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_total_1` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_a_net_2` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_a_brut_2` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_r_net_2` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_r_brut_2` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_total_2` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_a_net_3` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_a_brut_3` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_r_net_3` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_r_brut_3` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_total_3` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_a_net_4` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_a_brut_4` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_r_net_4` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_r_brut_4` decimal(6,2) unsigned DEFAULT NULL,
  `adulte_total_4` decimal(6,2) unsigned DEFAULT NULL,
  `enfant_a_net` decimal(6,2) unsigned DEFAULT NULL,
  `enfant_a_brut` decimal(6,2) unsigned DEFAULT NULL,
  `enfant_r_net` decimal(6,2) unsigned DEFAULT NULL,
  `enfant_r_brut` decimal(6,2) unsigned DEFAULT NULL,
  `enfant_total` decimal(6,2) unsigned DEFAULT NULL,
  `bebe_a_net` decimal(6,2) unsigned DEFAULT NULL,
  `bebe_a_brut` decimal(6,2) unsigned DEFAULT NULL,
  `bebe_r_net` decimal(6,2) unsigned DEFAULT NULL,
  `bebe_r_brut` decimal(6,2) unsigned DEFAULT NULL,
  `bebe_total` decimal(6,2) unsigned DEFAULT NULL,
  `handling_fees` decimal(10,2) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=128 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `prestation_types`;
CREATE TABLE `prestation_types` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `is_meal` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `name` varchar(20) NOT NULL,
  `photo` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `vols_new`;
CREATE TABLE `vols_new` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `vol_seul` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Indique si le vol est à utiliser comme vol seul plutôt que dans un séjour',
  `titre` varchar(100) COLLATE latin1_general_ci NOT NULL,
  `id_company` int(10) NOT NULL,
  `class_reservation` enum('Airline','Charter','Contingent') COLLATE latin1_general_ci NOT NULL,
  `sans_bagage` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'pour les vols seul',
  `monnaie` char(3) COLLATE latin1_general_ci DEFAULT NULL,
  `taux_change` float NOT NULL DEFAULT 0,
  `jours_depart` set('1','2','3','4','5','6','7') COLLATE latin1_general_ci NOT NULL DEFAULT '1,2,3,4,5,6,7',
  `code_apt_depart` char(3) COLLATE latin1_general_ci NOT NULL,
  `code_apt_transit` char(3) COLLATE latin1_general_ci DEFAULT NULL,
  `code_apt_arrive` char(3) COLLATE latin1_general_ci NOT NULL,
  `arrive_next_day` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 = arrivée même jour',
  `debut_vente` date NOT NULL,
  `fin_vente` date NOT NULL,
  `debut_voyage` date NOT NULL,
  `fin_voyage` date NOT NULL,
  PRIMARY KEY (`id`),
  KEY `code_apt_depart` (`code_apt_depart`),
  KEY `code_apt_arrive` (`code_apt_arrive`),
  KEY `debut_voyage` (`debut_voyage`),
  KEY `fin_voyage` (`fin_voyage`)
) ENGINE=InnoDB AUTO_INCREMENT=571 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `vol_prix`;
CREATE TABLE `vol_prix` (
  `id_prix_vol` int(10) NOT NULL AUTO_INCREMENT,
  `id_vol` int(10) NOT NULL,
  `surclassement` enum('eco','premium','business','first') COLLATE latin1_general_ci NOT NULL,
  `adulte_net` decimal(7,2) NOT NULL DEFAULT 0.00,
  `adulte_comm` decimal(7,2) NOT NULL DEFAULT 0.00,
  `adulte_vol_brut` decimal(7,2) NOT NULL DEFAULT 0.00,
  `adulte_taxe` decimal(7,2) NOT NULL DEFAULT 0.00,
  `adulte_total` decimal(7,2) NOT NULL DEFAULT 0.00,
  `enfant_net` decimal(7,2) NOT NULL DEFAULT 0.00,
  `enfant_comm` decimal(7,2) NOT NULL DEFAULT 0.00,
  `enfant_vol_brut` decimal(7,2) NOT NULL DEFAULT 0.00,
  `enfant_taxe` decimal(7,2) NOT NULL DEFAULT 0.00,
  `enfant_total` decimal(7,2) NOT NULL DEFAULT 0.00,
  `bebe_net` decimal(7,2) NOT NULL DEFAULT 0.00,
  `bebe_comm` decimal(7,2) NOT NULL DEFAULT 0.00,
  `bebe_vol_brut` decimal(7,2) NOT NULL DEFAULT 0.00,
  `bebe_taxe` decimal(7,2) NOT NULL DEFAULT 0.00,
  `bebe_total` decimal(7,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id_prix_vol`),
  UNIQUE KEY `id_vol` (`id_vol`,`surclassement`),
  CONSTRAINT `vol_prix_vols_FK` FOREIGN KEY (`id_vol`) REFERENCES `vols_new` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=142 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

DROP TABLE IF EXISTS `voyageurs`;
CREATE TABLE `voyageurs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `booking_type` enum('App\\Models\\Reservation','App\\Models\\Circuit','App\\Models\\Croisiere') COLLATE utf8mb4_unicode_ci NOT NULL,
  `adulte` tinyint(4) NOT NULL,
  `idx` tinyint(4) NOT NULL,
  `nom` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `prenom` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `titre` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `code_pays_nationalite` varchar(2) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `date_naissance` date DEFAULT NULL,
  `id_assurance` int(11) DEFAULT NULL,
  `options` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `booking_type_booking_id_adulte_idx` (`booking_type`,`booking_id`,`adulte`,`idx`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

