<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Croisiere extends Model
{
    protected $table = 'croisieres_new';
    public $timestamps = false;
    protected $fillable = [
        // 'id' int(10) NOT NULL AUTO_INCREMENT,
        'titre', // varchar(50) NOT NULL,
        'tour_code', // varchar(20) DEFAULT NULL,
        'id_lieu_dpt', // int(10) DEFAULT NULL,
        'id_lieu_arr', // int(10) DEFAULT NULL,
        'jours_depart', // set('1','2','3','4','5','6','7') NOT NULL DEFAULT '1,2,3,4,5,6,7',
        'dates_depart', // text DEFAULT NULL,
        'nb_nuit', // tinyint(3) unsigned NOT NULL DEFAULT 1,
        'type_repas', // enum('Sans repas','Petit déjeuner','Demi-pension','Pension complète','All Inclusive','Selon programme') NOT NULL DEFAULT 'Selon programme',
        'type_depart', // enum('quotidien','programmé') NOT NULL,
        'type_croisiere', // enum('maritime','fluviale') NOT NULL,
        'debut_validite', // date NOT NULL,
        'fin_validite', // date NOT NULL,
        'photo', // varchar(40) DEFAULT NULL,
        'remise_pct', // tinyint(3) unsigned DEFAULT 0,
        'remise_debut', // date DEFAULT NULL,
        'remise_fin', // date DEFAULT NULL,
        'remise_debut_voyage', // date DEFAULT NULL,
        'remise_fin_voyage', // date DEFAULT NULL,
        'remise_code_promo', // varchar(50) DEFAULT '',
        'inclus', // text DEFAULT NULL,
        'non_inclus', // text DEFAULT NULL,
        'id_vol', // int(15) NOT NULL DEFAULT 0,
        'monnaie', // char(3) DEFAULT NULL,
        'taux_change', // float NOT NULL DEFAULT 0,
        'taux_commission', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_nb_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_adulte_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_enfant_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_bebe_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_adulte_1_net_a', // decimal(8,2) DEFAULT NULL,
        'simple_adulte_1_net_b', // decimal(8,2) DEFAULT NULL,
        'simple_adulte_1_brut', // decimal(8,2) DEFAULT NULL,
        'simple_adulte_1_total', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_1_agemin', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_enfant_1_agemax', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_enfant_1_net', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_1_brut', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_1_total', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_2_agemin', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_enfant_2_agemax', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_enfant_2_net', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_2_brut', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_2_total', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_3_agemin', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_enfant_3_agemax', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'simple_enfant_3_net', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_3_brut', // decimal(8,2) DEFAULT NULL,
        'simple_enfant_3_total', // decimal(8,2) DEFAULT NULL,
        'simple_bebe_1_agemax', // tinyint(3) DEFAULT NULL,
        'simple_bebe_1_net', // decimal(8,2) DEFAULT NULL,
        'simple_bebe_1_brut', // decimal(8,2) DEFAULT NULL,
        'simple_bebe_1_total', // decimal(8,2) DEFAULT NULL,
        'double_nb_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_adulte_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_enfant_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_bebe_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_adulte_1_net', // decimal(8,2) DEFAULT NULL,
        'double_adulte_1_brut', // decimal(8,2) DEFAULT NULL,
        'double_adulte_1_total', // decimal(8,2) DEFAULT NULL,
        'double_adulte_2_net', // decimal(8,2) DEFAULT NULL,
        'double_adulte_2_brut', // decimal(8,2) DEFAULT NULL,
        'double_adulte_2_total', // decimal(8,2) DEFAULT NULL,
        'double_enfant_1_agemin', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_enfant_1_agemax', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_enfant_1_net', // decimal(8,2) DEFAULT NULL,
        'double_enfant_1_brut', // decimal(8,2) DEFAULT NULL,
        'double_enfant_1_total', // decimal(8,2) DEFAULT NULL,
        'double_enfant_2_agemin', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_enfant_2_agemax', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_enfant_2_net', // decimal(8,2) DEFAULT NULL,
        'double_enfant_2_brut', // decimal(8,2) DEFAULT NULL,
        'double_enfant_2_total', // decimal(8,2) DEFAULT NULL,
        'double_enfant_3_agemin', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_enfant_3_agemax', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'double_enfant_3_net', // decimal(8,2) DEFAULT NULL,
        'double_enfant_3_brut', // decimal(8,2) DEFAULT NULL,
        'double_enfant_3_total', // decimal(8,2) DEFAULT NULL,
        'double_bebe_1_agemax', // tinyint(1) DEFAULT NULL,
        'double_bebe_1_net', // decimal(8,2) DEFAULT NULL,
        'double_bebe_1_brut', // decimal(8,2) DEFAULT NULL,
        'double_bebe_1_total', // decimal(8,2) DEFAULT NULL,
        'tripple_nb_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'tripple_enfant_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'tripple_adulte_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'tripple_adulte_1_net', // decimal(8,2) DEFAULT NULL,
        'tripple_adulte_1_brut', // decimal(8,2) DEFAULT NULL,
        'tripple_adulte_1_total', // decimal(8,2) DEFAULT NULL,
        'tripple_adulte_2_net', // decimal(8,2) DEFAULT NULL,
        'tripple_adulte_2_brut', // decimal(8,2) DEFAULT NULL,
        'tripple_adulte_2_total', // decimal(8,2) DEFAULT NULL,
        'tripple_adulte_3_net', // decimal(8,2) DEFAULT NULL,
        'tripple_adulte_3_brut', // decimal(8,2) DEFAULT NULL,
        'tripple_adulte_3_total', // decimal(8,2) DEFAULT NULL,
        'quatre_nb_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'quatre_adulte_max', // tinyint(3) unsigned NOT NULL DEFAULT 0,
        'quatre_adulte_1_net', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_1_brut', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_1_total', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_2_net', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_2_brut', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_2_total', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_3_net', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_3_brut', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_3_total', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_4_net', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_4_brut', // decimal(8,2) DEFAULT NULL,
        'quatre_adulte_4_total', // decimal(8,2) DEFAULT NULL,
    ];

    public function prestations() {
        return $this->morphMany(Prestation::class, 'prestationable');
    }
 }